export const allFooters = [
  {
    id: 1,
    title: "Footer 1",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=1.webp",
    isComingSoon: true,
  },
  {
    id: 2,
    title: "Footer 2",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=2.webp",
    isComingSoon: true,
  },
  {
    id: 3,
    title: "Footer 3",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=3.webp",
    isComingSoon: true,
  },
  {
    id: 4,
    title: "Footer 4",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=4.webp",
    isComingSoon: true,
  },
  {
    id: 5,
    title: "Footer 5",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=5.webp",
    isComingSoon: true,
  },
  {
    id: 6,
    title: "Footer 6",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=6.webp",
    isComingSoon: true,
  },
  {
    id: 7,
    title: "Footer 7",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=7.webp",
    isComingSoon: true,
  },
  {
    id: 8,
    title: "Footer 8",
    html: ``,
    preview: virfice.assetsBase + "/ready-blocks/footer=8.webp",
    isComingSoon: true,
  },
];
